CFSoft/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('', include( ('bases.urls','bases'), namespace='bases' ) ),
    path('admin/', admin.site.urls),
]

api/urls.py
from django.urls import path, include
from .views import ProductoList, ProductoDetalle, \
    ClienteList


urlpatterns = [
 	path('v1/productos/',ProductoList.as_view(),name='producto_list'),
    path('v1/productos/<str:codigo>',ProductoDetalle.as_view(),name='producto_detalle'),
    path('v1/clientes/',ClienteList.as_view(),name='cliente_list')
    
]

cfsoft/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from Clientes import views 
from productos import views
from ventas import views

"""path('Clientes/', include(('Clientes.urls','Clientes'), namespace='clientes')),"""

urlpatterns = [
    path('', include(('bases.urls','bases'), namespace='bases')), 
    path('proveedor/', include(('proveedor.urls', 'proveedor'), namespace='proveedor')),
    path('productos/', include(('productos.urls','productos'), namespace='productos')),
    path('inventario/', include(('inventario.urls', 'inventario'), namespace='inv')),
    path('ventas/', include(('ventas.urls', 'ventas'), namespace='ventas')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
    path('admin/', admin.site.urls),

]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

proveedor/urls.py
# Django
from django.urls import path

# Local
from .views import ProveedorView, ProveedorNew, ProveedorEdit, ProveedorDel, PagoView, ComprasDetEdit,ComprasDetView, \
    ComprasView, compras, CompraDetDelete, OrdenComprasView, orden_compras, OrdenView, clienteInactivar, realizarPago, detalle_compras,notaCredito
from .reportes import reporte_compras, imprimir_compra, imprimir_compras_rang

urlpatterns = [
    path('proveedor/', ProveedorView.as_view(), name='proveedor_list'),
    path('proveedor/new', ProveedorNew.as_view(), name='proveedor_new'),
    path('proveedor/edit/<int:pk>', ProveedorEdit.as_view(), name='proveedor_edit'),
    path('proveedor/delete/<int:pk>', ProveedorDel.as_view(), name='proveedor_del'),
    path('compras/listado', reporte_compras, name='compras_print_all'),
    path('compras/<int:compras_id>/imprimir', imprimir_compra, name="compras_print_one"),
    path('compras/imprimir-todas/<str:f1>/<str:f2>', imprimir_compras_rang, name="compras_print_rang"),
    #path('compras/imprimir-todas/<str:f1>/<str:f2>', imprimir_compras_rang, name="pruebas_compras"),

    path('compras/', ComprasView.as_view(), name="compras_list"),
    path('compras_detalle/', ComprasDetView.as_view(), name="compras_det_list"), 
    path('orden_compras/', OrdenComprasView.as_view(), name="orden_compras_list"),
    path('pago/', PagoView.as_view(), name="pago_list"),
    path('compras/new', compras, name="compras_new"),
    path('orden_compras/new', orden_compras, name="orden_compras_new"),
    path('compras/edit/<int:compra_id>', compras, name="compras_edit"),  
    path('compras_detalle/<int:compra_id>/edit/<int:pk>', ComprasDetEdit.as_view(), name="compras_detalle_edit"),
    #path('compras_detalles/edit/<int:id>', ComprasDetEdit.as_view(), name="compras_det_edit"),
    path('compras_detalles/edit/<int:pk>', ComprasDetEdit.as_view(), name="compras_det_edit"),
    path('orden_compras/edit/<int:compra_id>', orden_compras, name="orden_compras_edit"),
    path('compras/<int:compra_id>/delete/<int:pk>', CompraDetDelete.as_view(), name="compras_del"),
    path('orden_compra/estado/<int:id>',clienteInactivar, name="cliente_inactivar"),
    path('pago/<int:id>',realizarPago, name="realizar_pago"),
    path('proveedor/buscar-orden',OrdenView.as_view(), name='buscar_compra'),

    path('compras/notaCred/<int:id>', notaCredito, name="nota_credito")
]

bases/models.py
# Django
from django.db import models
from django.contrib.auth.models import User
from django_userforeignkey.models.fields import UserForeignKey


class ClaseModeloInv(models.Model):
    estado = models.BooleanField(default=True)
    fc = models.DateTimeField(auto_now_add=True)
    fm = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class ClaseModelo(models.Model):
    estado = models.BooleanField(default=True)
    fc = models.DateTimeField(auto_now_add=True, null=True)
    fm = models.DateTimeField(auto_now=True)
    uc = models.ForeignKey(User, on_delete=models.CASCADE)
    um = models.IntegerField(blank=True, null=True)

    class Meta:
        abstract = True


class ClaseModelo2(models.Model):
    estado = models.BooleanField(default=True)
    fc = models.DateTimeField(auto_now_add=True, null=True)
    fm = models.DateTimeField(auto_now=True, null=True)
    uc = UserForeignKey(auto_user_add=True, related_name='+')
    um = UserForeignKey(auto_user=True, related_name='+')

    class Meta:
        abstract = True


class ClaseModeloUsuario(models.Model):
    cedula = models.CharField(max_length=50, blank=True)
    nombre = models.CharField(max_length=50, blank=True)
    apellido = models.CharField(max_length=50, blank=True)
    ruc = models.CharField(max_length=50, blank=True)
    email = models.CharField(max_length=50, blank=True)
    telefono = models.CharField(max_length=50, blank=True)
    direccion = models.CharField(max_length=50, blank=True)

    class Meta:
        abstract = True

class Idioma(models.Model):
    nombre = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural = "Idiomas"

    def __str__(self):
        return self.nombre


class Frase(models.Model):
    idioma = models.ForeignKey(Idioma,on_delete=models.CASCADE)
    autor = models.CharField(max_length=50,default="Anónimo")
    frase = models.TextField(null=True,blank=True)

    class Meta:
        verbose_name_plural = "Frases"

    def __str__(self):
        return "{} - {}".format(self.autor,self.idioma)

proveedor/models.py
from django.db import models
# Para los signals
from django.db.models.signals import post_save, post_delete
from django.urls import reverse
from django.dispatch import receiver
from django.db.models import Sum
from bases.models import ClaseModelo, ClaseModeloUsuario
from productos.models import Producto
from datetime import datetime



class Proveedor(ClaseModelo, ClaseModeloUsuario):
    """cedula = models.CharField(max_length=50, blank=True)
    ruc = models.CharField(max_length=50, blank=True)
    nombre = models.CharField(max_length=50, blank=True)
    apellido = models.CharField(max_length=50, blank=True)
    telefono = models.CharField(max_length=50, blank=True)
    direccion = models.CharField(max_length=50, blank=True)"""

    def __str__(self):
        return '{}'.format(self.cedula)

    class Meta:
        verbose_name_plural = 'Proveedores'


class ComprasEnc(ClaseModelo):
    fecha_compra = models.DateTimeField(null=True, blank=True)
    #fecha_compra = models.DateTimeField(auto_now_add=True)
    observacion = models.TextField(blank=True, null=True)
    no_factura = models.CharField(max_length=100, default=0)
    cantidad_cuotas = models.CharField(max_length=12, default='')
    no_timbrado = models.CharField(max_length=8)
    fecha_fin_timbrado = models.DateField(null=True, blank=True)
    fecha_ini_timbrado = models.DateField(null=True, blank=True)
    fecha_factura = models.DateField()
    sub_total = models.FloatField(default=0)
    descuento = models.FloatField(default=0)
    total = models.FloatField(default=0)

    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE)

    def __str__(self):
        #return '{}'.format(self.observacion)
        return '{}'.format(self.id)

    def save(self, **kwargs):
        #self.observacion = self.observacion.upper() 
        if self.sub_total == None  or self.descuento == None:
            self.sub_total = 0
            self.descuento = 0

        self.total = self.sub_total - self.descuento
        super(ComprasEnc, self).save()

    class Meta:
        verbose_name_plural = "Encabezado Compras"
        verbose_name = "Encabezado Compra"


class ComprasDet(ClaseModelo):
    compra = models.ForeignKey(ComprasEnc, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.BigIntegerField(default=0)
    dif_cantidad = models.IntegerField(default=0)
    precio_prv = models.FloatField(default=0)
    sub_total = models.FloatField(default=0)
    descuento = models.FloatField(default=0)
    total = models.FloatField(default=0)
    costo = models.FloatField(default=0)

    def __str__(self):
        #return '{}'.format(self.producto)
        return f'{self.compra}, {self.producto}, {self.cantidad}, {self.precio_prv}, {self.sub_total} , {self.total}'

    def save(self, **kwargs):
        self.cantidad = self.cantidad + self.dif_cantidad
        self.sub_total = float(float(int(self.cantidad)) * float(self.precio_prv))
        self.total = self.sub_total - float(self.descuento)
        super(ComprasDet, self).save()

    class Meta:
        verbose_name_plural = "Detalles Compras"
        verbose_name = "Detalle Compra"


@receiver(post_delete, sender=ComprasDet)
def detalle_compra_borrar(sender, instance, **kwargs):
    id_producto = instance.producto.id
    id_compra = instance.compra.id

    enc = ComprasEnc.objects.filter(pk=id_compra).first()
    if enc:
        sub_total = ComprasDet.objects.filter(compra=id_compra).aggregate(Sum('sub_total'))
        descuento = ComprasDet.objects.filter(compra=id_compra).aggregate(Sum('descuento'))
        enc.sub_total = sub_total['sub_total__sum']
        enc.descuento = descuento['descuento__sum']
        enc.save()

    prod = Producto.objects.filter(pk=id_producto).first()
    if prod:
        cantidad = int(prod.existencia) - int(instance.cantidad)
        prod.existencia = cantidad
        prod.save()


@receiver(post_save, sender=ComprasDet)
def detalle_compra_guardar(sender, instance, **kwargs):
    id_producto = instance.producto.id
    id_compra = instance.compra.id
    fecha_compra=instance.compra.fecha_compra
    precio_compra = instance.precio_prv

    enc = ComprasEnc.objects.filter(pk=id_compra).first()
    #caja = Caja.objects.filter(comp= id_compra).first()
    #import pdb; pdb.set_trace()

    if enc:
        sub_total = ComprasDet.objects.filter(compra=id_compra).aggregate(Sum('sub_total'))
        descuento = ComprasDet.objects.filter(compra=id_compra).aggregate(Sum('descuento'))
        enc.sub_total = sub_total['sub_total__sum']
        enc.descuento = descuento['descuento__sum']
        enc.save()

    cantidad = enc.cantidad_cuotas
    monto_cuenta = enc.sub_total

    deuda = PagoProveedor.objects.filter(compra_id=id_compra).first()
    if deuda:
        deuda.monto_mensual = monto_cuenta/int(cantidad)
        deuda.cantidad_cuotas= cantidad
        deuda.monto_total_pag = 0
        deuda.estado_cuenta = 'Pendiente'
        deuda.save()


    prod = Producto.objects.filter(pk=id_producto).first()
    if prod:
        if instance.dif_cantidad < 0:
             cantidad = int(prod.existencia) - int(instance.cantidad)
        else:
            cantidad = int(prod.existencia) + int(instance.cantidad)
        prod.existencia = cantidad
        prod.ultima_compra=fecha_compra
        prod.precio = precio_compra
        prod.save()

    # Caja 
    from ventas.models import Caja

    c = Caja.objects.filter(comp=id_compra).first()
    # si ya existe la caja entonces editamos
    if c:
        #c = list(c)
        #for item in c:
        id_caja = c.id
        caja = Caja.objects.filter(id=id_caja).first()                                                                                                                                                      
        #import pdb; pdb.set_trace()
        caja.saldo_actual = caja.salida + caja.saldo_actual
        caja.salida = enc.total
        caja.saldo_actual = caja.saldo_actual - caja.salida
        caja.save()

        # Calculo para ajustar los saldos
        """cajaList = Caja.objects.all()
        cajaList = list(cajaList)
        lastid = cajaList[-1].id 
        import pdb; pdb.set_trace()
        if lastid > id_caja :
            #cajaList = list(cajaList)
            saldo_actual = caja.saldo_actual
            i = id_caja + 1
            import pdb; pdb.set_trace()
            while i < lastid or i == lastid:
                caja = Caja.objects.filter(id=i).first()
                if caja.entrada > 0:
                    caja.saldo_actual = saldo_actual + caja.entrada
                    saldo_actual = caja.saldo_actual
                else:
                    caja.saldo_actual = saldo_actual - caja.salida
                    saldo_actual = caja.saldo_actual
                i=i+1
                caja.save()"""
    # si no existe la caja crea un nuevo registro           
    else:
        cant = Caja.objects.all().count()
        cajalist = Caja.objects.all()
        total_detalle = enc.total
        saldo = cajalist[cant-1].saldo_actual
        saldo_actual = saldo - total_detalle 

        caja = Caja (
            comp = enc,
            #fecha = datetime.today(),
            descripcion = 'COMPRA',
            entrada = 0,
            salida = total_detalle,
            saldo_actual = saldo_actual
        )

        caja.save()

    #import pdb;pdb.set_trace()

class OrdenComprasEnc(ClaseModelo):
    fecha_compra = models.DateField(null=True, blank=True)
    observacion = models.TextField(blank=True, null=True)
#    no_factura = models.CharField(max_length=100)
#    fecha_factura = models.DateField()
    sub_total = models.FloatField(default=0)
    descuento = models.FloatField(default=0)
    total = models.FloatField(default=0)

    #proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE)

    def __str__(self):
        #return '{}'.format(self.total)
        return f'{self.observacion}, {self.total}'

    def save(self, **kwargs):
        self.observacion = self.observacion.upper()
        if self.sub_total == None  or self.descuento == None:
            self.sub_total = 0
            self.descuento = 0

        self.total = self.sub_total - self.descuento
        super(OrdenComprasEnc, self).save()

    class Meta:
        verbose_name_plural = "Encabezado de Orden Compras"
        verbose_name = "Encabezado Orden Compra"

class OrdenComprasDet(ClaseModelo):
    compra = models.ForeignKey(OrdenComprasEnc, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.BigIntegerField(default=0)
    precio_prv = models.FloatField(default=0)
    sub_total = models.FloatField(default=0)
    descuento = models.FloatField(default=0)
    total = models.FloatField(default=0)
    costo = models.FloatField(default=0)
    estado_compra = models.CharField(max_length=12, default= 'En proceso' ) 

    def __str__(self):
        #return '{}'.format(self.producto)
        return f'{self.producto}, {self.cantidad}, {self.precio_prv},{self.descuento},{self.total}'

    def save(self, **kwargs):
        self.sub_total = float(float(int(self.cantidad)) * float(self.precio_prv))
        self.total = self.sub_total - float(self.descuento)
        super(OrdenComprasDet, self).save()
    

    class Meta:
        verbose_name_plural = "Detalles orden Compras"
        verbose_name = "Detalle Orden Compra"
#fin de clase orden compra enc y detalle

#Modelo pagos_proveedor 

class PagoProveedor(models.Model):
    compra = models.ForeignKey(ComprasEnc, on_delete=models.CASCADE)
    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE)
    cantidad_cuotas = models.CharField(max_length=3, default='')
    #cant_cuotas_pagadas = models.BigIntegerField(default=0)
    monto_mensual = models.FloatField(default=0)
    monto_total_pag = models.FloatField(default=0)

venta/models.py
#Django
from django.db import models

#Local
from bases.models import ClaseModelo, ClaseModelo2
from Clientes.models import Cliente
from productos.models import Producto


""" Encabezado de la factura """

class FacturaEnc(ClaseModelo2):
	cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
	fecha = models.DateTimeField(auto_now_add=True)
	sub_total = models.FloatField(default=0)
	descuento = models.FloatField(default=0)
	total = models.FloatField(default=0)

def __str__(self):
	return '{}'.format(self.id)

def save(self):
	self.total = self.sub_total - self.descuento
	super(facturaEnc,self).save()

class Meta:
	verbose_name_plural = "Encabezado de Facturas"
	verbose_name = "Encabezado Factura"


 
""" Detalle de la factura """

class FacturaDet(ClaseModelo2):
	factura = models.ForeignKey(FacturaEnc, on_delete=models.CASCADE)
	producto = m odels.ForeignKey(Producto, on_delete=models.CASCADE)
	cantidad = models.BigIntegerField(default=0)
	precio = models.FloatField(default=0)
	sub_total = models.FloatField(default=0)
	descuento = models.FloatField(default=0)
	total = models.FloatField(default=0)

def __str__(self):
	return '{}'.format(self.producto)	

def save(self):
	self.sub_total = float(float(int(self.cantidad)) * float(self.precio))
	self.total = self.sub_total - float(self.descuento)
	super(FacturaDet, self).save()

class Meta:
	verbose_name_plural = "Detalles Facturas"
	verbose_name = "Detalle Factura"

proveedor/templates/prov/compras_det_form.html
{% extends 'base/base.html' %}

{% block page_content %}
<form method="POST" action="{% url 'proveedor:compras_detalle_edit' obj.compra.id obj.pk %}" class="form-inline">
	{% csrf_token %}
		<div class="col-xl-6 col-md-6 mb-6">
			{% if obj %}
				<div class="card border-left-warning shadow h-100 py-2">
			{% else %}	
			  	<div class="card border-left-succes shadow h-100 py-2">
			{% endif %}
			<div class="card-body">
				<div class="row no-gutters align-items-center">
			 	   <div class="col mr-2">
			    	   <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
			     	     	{% if obj %} Editar Detalle{% else %} Nuevo Detalle Compra {% endif %} </div>
			       	   		<div class="dropdown-divider"></div>
			        			<div class="row">
			          				 <div class="col-10">
			          					<div class="input-group">
											{{ form.as_p }}   
			          					</div>  
			          				</div> 
			        			</div>
			        		<div class="dropdown-divider"></div>
			        			<div class="row">
			        				<div class="col">
			        					<button type="submit" class="btn btn-danger"><span class="fa fa-save"></span>Guardar</button>  
			        					<a href="{% url 'proveedor:compras_edit' obj.compra.id %}" class="btn btn-succes"><span class="fa fa-undo"></span>Cancelar</a>
			        			</div>
			        		</div>
			     	  </div>
			    </div>
			</div>
		</div>
</form>

{% endblock %}
{% block js_page %}
{% endblock %}

proveedor/templates/prov/compras_list.html
{% extends 'base/base.html' %}

{% block page_content %}
    <div class="card shadow mb-4">
       
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Listado de Compras</h6>
            <div class="dropdown no-arrow">
                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                    <div class="dropdown-header">Acciones:</div>
                    <a class="dropdown-item" href="{% url 'proveedor:compras_new' %}"><i class="far fa-calendar-plus"></i>Nueva</a>
                    <a class="dropdown-item" href="{% url 'proveedor:compras_print_all' %}" target="reportes"><i class="fas fa-print"></i> Listado</a>
                </div>
            </div>
        </div>
        <!-- Card Body -->
        <div class = "card-body">
            <div class = "row">
                <div class = "col-md-4">
                 <input type = "text" class = "form-class" name = "f1" id = "f1" readonly>
                </div>
                <div class = "col-md-4" >
                 <input type = "text" class = "form-class" name = "f2" id = "f2" readonly>
                </div>
                <div class = " col-md-4 " >
                 <button class = "btn btn-warning" type = "button" id = "btnPrint"> Imprimir </button >
                </div>
            </div>
            <hr>

            {% if not obj %}
                <div class="alert alert-info">No hay Compras</div>
            {% endif %}
            <table class="table table-striped table-hover dt-responsive nowrap" style="width: 100%">
                <thead>
                    <th>id</th>
      		        <th>Fecha</th>
      		        <th>Observacion</th>
                    <th>No. Timbrado</th>
      		        <th>No. Factura</th>
      		        <th>F. Factura</th>
      		        <th>sub Total</th>
                    <th>Descuento</th>
                    <th>Total</th>
      		        <th class="all">Acciones</th>
                </thead>
                <tbody>
                    {% for item in obj %}
                    <tr>
                        <td>{{ item.id }}</td>
      				    <td>{{ item.fecha_compra }}</td>
      				    <td>{{ item.observacion }}</td>
                        <td>{{ item.no_timbrado }}</td>
      				    <td>{{ item.no_factura }}</td>
      				    <td>{{ item.fecha_factura }}</td>
      				    <td>{{ item.sub_total }}</td>
                        <td>{{ item.descuento }}</td>
                        <td>{{ item.total }}</td>
                        <td>
                            <a class="btn btn-warning btn-circle" href="{% url 'proveedor:compras_edit' item.id %}"><i class="far fa-edit" ></i></a>
                            <a class="btn btn-success btn-circle" href="{% url 'proveedor:compras_print_one' item.id %}" target="reportes"><i class="fas fa-print"></i></a>
                            <a class="btn btn-info" href="{% url 'proveedor:nota_credito' item.id %} ">Nota de Crédito</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block js_page %}
    <script>
        //call the datatables jQuery plugin
        $(document).ready(function () {
            $('.table').DataTable({
                "languaje": {
                    "sProcessing": "Procesando...",
                    "sLengthMenu": "Mostrar _MENU_registros",
                    "sZerorecords": "No se encontraron resultados",
                    "sEmptyTable": "Ningun dato disponible en esta tabla",
                    "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando registro del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered": "(Filtrando de un total de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sSearch": "Buscar:",
                    "sUrl": "",
                    "sInfoThousands": ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst": "<span class='fa fa-angle-double-left'></span>",
                        "sLast": "<span class='fa fa-angle-double-right'></span>",
                        "sNext": "<span class='fa fa-angle-right'></span>",
                        "sPrevious": "<span class='fa fa-angle-left'></span>"
                    },
                    "oAria": {
                        "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    }
                }
            });
        });
    </script>

    <script>

    $(function () {

        $("#f1, #f2").datetimepicker({
            format: 'Y-m-d',
            timepicker: false
        });

        $("#btnPrint").click(function(e){
            e.preventDefault();
            var f1,f2;
            f1 = $("#f1").val();
            f2 = $("#f2").val();
            if(f1=="" || f1==null){
                f1="2021-11-01";
            }
            if(f2=="" || f2==null){
                var d = new Date();
                var f2 = d.getFullYear() + "-" + (d.getMonth()+1) + "-" + d.getDate();
            }
            var url = "imprimir-todas/" + f1 + "/" + f2;

            window.open(url,'compras');
        });
    });
    </script>
{% endblock %}

proveedor/templates/prov/pago_form.html
{% extends 'base/base.html' %}
{% block page_content %}
    <form method="POST" class="form-inline">
        {% csrf_token %}
        <div class="col-xl-6 col-md-6 mb-6">
            {% if obj %}
            <div class="card border-left-warning shadow h-100 py-2">
            {% else %}
            <div class="card border-left-success shadow h-100 py-2">
            {% endif %}
                <div class="card-body">
                <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                {% if obj  %} Editar {% else %} Nuevo {% endif %} Proveedor
                            </div>
                                <div class="dropdown-divider"></div>
                            <div class="row">
                                <div class="col-10">
                                    <div class="input-group">
                                        <p><input type="text" name="cedula" maxlength="100" class="form-control" required id="id_cedula" placeholder="Cédula" value="{% if obj %} {{ obj.cedula }} {% endif %}"></p>
			          						<p><input type="text" name="nombre" maxlength="100" class="form-control" required id="id_nombre" placeholder="Nombre" value="{% if obj %} {{ obj.nombre }} {% endif %}"></p>
			          						<p><input type="text" name="apellido" maxlength="100" class="form-control" required id="id_apellido" placeholder="Apellido" value="{% if obj %} {{ obj.apellido }} {% endif %}"></p>
			          						<p><input type="text" name="ruc" maxlength="100" class="form-control" required id="id_ruc" placeholder="RUC" value="{% if obj %} {{ obj.ruc }} {% endif %}"></p>
			          						<p><input type="text" name="email" maxlength="100" class="form-control" required id="id_email" placeholder="Email" value="{% if obj %} {{ obj.email }} {% endif %}"></p>
			          						<p><input type="text" name="telefono" maxlength="100" class="form-control" required id="id_telefono" placeholder="Tel/Cel" value="{% if obj %} {{ obj.telefono }} {% endif %}"></p>
			          						<p><input type="text" name="direccion" maxlength="100" class="form-control" required id="id_direccion" placeholder="Dirección" value="{% if obj %} {{ obj.direccion }} {% endif %}"></p>
                                    </div>
                                </div>
                            </div>
			        	        <div class="dropdown-divider"></div>
                                <div class="row">
                                    <div class="col">
                                        <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span>Guardar</button>
                                        <a href="{% url 'proveedor:proveedor_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
                                    </div>
                                </div>
                        </div>
                </div>
                </div>
            </div>
            </div>
        </div>
    </form>
{% endblock %}
{% block js_page %}
{% endblock %}

proveedor/templates/prov/proveedor_del.html
{% extends 'base/base.html' %}
{% block page_content %}
    <form method="POST" class="form-inline">
        {% csrf_token %}
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-danger shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">¿Eliminar {{ obj.nombre }}?</div>
                            <button type="submit" class="btn btn-danger"><i class="far fa-question-circle"></i>Si, Eliminar</button>
                            <a href="{% url 'proveedor:proveedor_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
                        </div>
                        <div class="col-auto">
                            <i class="far fa-question-circle fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
              </div>
        </div>
    </form>
{% endblock %}
{% block js_page %}
{% endblock %}