CFSoft/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('', include( ('bases.urls','bases'), namespace='bases' ) ),
    path('admin/', admin.site.urls),
]

api/urls.py
from django.urls import path, include
from .views import ProductoList, ProductoDetalle, \
    ClienteList


urlpatterns = [
 	path('v1/productos/',ProductoList.as_view(),name='producto_list'),
    path('v1/productos/<str:codigo>',ProductoDetalle.as_view(),name='producto_detalle'),
    path('v1/clientes/',ClienteList.as_view(),name='cliente_list')
    
]

cfsoft/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from Clientes import views 
from productos import views
from ventas import views

"""path('Clientes/', include(('Clientes.urls','Clientes'), namespace='clientes')),"""

urlpatterns = [
    path('', include(('bases.urls','bases'), namespace='bases')), 
    path('proveedor/', include(('proveedor.urls', 'proveedor'), namespace='proveedor')),
    path('productos/', include(('productos.urls','productos'), namespace='productos')),
    path('inventario/', include(('inventario.urls', 'inventario'), namespace='inv')),
    path('ventas/', include(('ventas.urls', 'ventas'), namespace='ventas')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
    path('admin/', admin.site.urls),

]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

productos/urls.py
from django.urls import path

#Local
from productos.views import ProductoView, ProductoNew, ProductoEdit, ProductoDel, InvProductoEdit, ProductoInvView, NotaCreditoView
from .reportes import imprimir_nota

urlpatterns = [
	path('productos/',ProductoView.as_view(), name='producto_list'),
	path('notas_creditos/',NotaCreditoView.as_view(), name='nota_credito_list'), 
	path('inv-productos/',ProductoInvView.as_view(), name='producto_inv_list'),
	path('productos/new',ProductoNew.as_view(), name='producto_new'),
	path('productos/edit/<int:pk>',ProductoEdit.as_view(), name='producto_edit'),
	path('Inventarioproductos/edit/<int:pk>',InvProductoEdit.as_view(), name='inv_producto_edit'),
	path('productos/delete/<int:pk>',ProductoDel.as_view(), name='producto_del'),
	path('notas_creditos/<int:id>/imprimir', imprimir_nota, name="nota_credito_print"),
]

productos/models.py
'''Modelo de productos'''
from django.db import models

from bases.models import ClaseModelo,ClaseModelo2
from django.utils import timezone
from django.db.models.signals import post_save
from django.dispatch import receiver


class Producto(ClaseModelo):
    """Modelo de producto"""
    codigo = models.CharField(max_length=20, unique=True, blank=False, default='cod_def' )
    product_name = models.CharField(max_length=50)

    unidad_medida = models.CharField(max_length=5)

    categoria = models.CharField(max_length=30)

    marca = models.CharField(max_length=30)

    precio = models.FloatField(default=0)
    existencia = models.FloatField(default=0)

    ultima_compra = models.DateField(null=True, blank=True)

    descripcion = models.CharField(max_length=200,default='.')

    def __str__(self):
        return '{}'.format(self.id)
        # return f'{self.name}, {self.checkIn}, {self.checkOut}, {self.occupant}'

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Producto,self).save()

    class Meta:
        verbose_name_plural = "Productos"
        """unique_together = ('codigo')"""


class AjusteInventario(Producto):
    """Modelo de Ajuste inventario"""


    def __str__(self):
        #return '{}'.format(self.product_name)
        return f'{self.product_name}, {self.existencia}'

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Producto,self).save()

    class Meta:
        verbose_name_plural = "Productos Ajustados"


class NotaCredito(ClaseModelo2):
    no_factura = models.CharField(max_length=100, default=0)
    producto = models.CharField(max_length=50, null=True)
    descripcion = models.CharField(max_length=200,default='.')
    cantidad = models.BigIntegerField(default=0)
    precio = models.FloatField(default=0)
    total = models.FloatField(default=0) 
    gravada = models.FloatField(default=0)
    iva = models.FloatField(default=0)

    def __str__(self):
        return '{}'.format(self.id)

    def save(self):
        super(NotaCredito,self).save()

    class Meta:
        verbose_name_plural = "Notas de Creditos"

productos/forms.py
# Django
from django import forms
# Local
from .models import Producto


# La vista llama a este formulario

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['codigo','product_name', 'unidad_medida','existencia','estado',
                  'categoria', 'marca', 'precio']

        labels = {'codigo':'codigo',
                'product_name': "Nombre Producto",
                  'unidad_medida': "Unidad de Medida",
                  'categoria': "Categoria",
                  'marca': "Marca",
                  'precio': 'Precio',
                  'estado': 'estado'}
        # Modificar tipo de datos.
        widget = {'product_name': forms.TextInput,
                  'categoria': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })
        self.fields ['existencia'].widget.attrs['readonly'] = True
        self.fields ['precio'].widget.attrs['readonly'] = True   

class InvProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['codigo','product_name', 'unidad_medida','existencia','estado',
                  'categoria', 'marca', 'precio']

        labels = {'codigo':'codigo',
                'product_name': "Nombre Producto",
                  'unidad_medida': "Unidad de Medida",
                  'categoria': "Categoria",
                  'marca': "Marca",
                  'precio': 'Precio',
                  'estado': 'estado'}
        # Modificar tipo de datos.
        widget = {'product_name': forms.TextInput,
                  'categoria': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })
        self.fields ['existencia'].widget.attrs['readonly'] = False
        self.fields ['codigo'].widget.attrs['readonly'] = True
        self.fields ['product_name'].widget.attrs['readonly'] = True
        self.fields ['unidad_medida'].widget.attrs['readonly'] = True
        self.fields ['categoria'].widget.attrs['readonly'] = True
        self.fields ['marca'].widget.attrs['readonly'] = True
        self.fields ['precio'].widget.attrs['readonly'] = True

productos/views.py
from django.shortcuts import redirect, render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, \
    PermissionRequiredMixin
from django.contrib import messages
from django.urls import reverse_lazy

from .models import Producto, NotaCredito
from .forms import ProductoForm, InvProductoForm


# Create your views here.
class ProductoView(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    permission_required = "productos.view_producto"
    model = Producto
    template_name = "productos/producto_list.html"
    context_object_name = "obj"
    login_url = 'bases:login'

class ProductoInvView(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    permission_required = "productos.view_producto"
    model = Producto
    template_name = "productos/producto_inv_list.html"
    context_object_name = "obj"
    login_url = 'bases:login'


class ProductoNew(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
    permission_required = "productos.add_producto"
    Model = Producto
    template_name = "productos/producto_form.html"
    context_object_name = "obj"
    form_class = ProductoForm
    success_url = reverse_lazy("productos:producto_list")
    login_url = "bases:login"

    # Para obtener el usuario que esta logueado
    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)


class ProductoEdit(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
    permission_required = "productos.change_producto"
    model = Producto
    template_name = "productos/producto_form.html"
    context_object_name = "obj"
    form_class = ProductoForm
    success_url = reverse_lazy("productos:producto_list")
    login_url = "bases:login"

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)

class InvProductoEdit(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
    permission_required = "productos.change_producto"
    model = Producto
    template_name = "productos/producto_form.html"
    context_object_name = "obj"
    form_class = InvProductoForm
    success_url = reverse_lazy("productos:producto_list")
    login_url = "bases:login"

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)

class ProductoDel(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):
    permission_required = "productos.delete_producto"
    model = Producto
    template_name = "productos/producto_del.html"
    context_object_name = "obj"
    success_url = reverse_lazy("productos:producto_list")


class NotaCreditoView(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    permission_required = "productos.view_producto"
    model = NotaCredito
    template_name = "productos/nota_credito_list.html"
    context_object_name = "obj"
    login_url = 'bases:login'



def producto_inactivar(request, id): 
    prod = Producto.objects.filter(pk=id).first()
    contexto= {}
    template_name = "productos/producto_del.html"

    if not prod:
        return redirect("productos:producto_list") 
    
    if request.method == 'GET':
        contexto= {'obj':prod}
    
    if request.method == 'POST':
        prod.estado = False 
        prod.save()
        return redirect("producto:producto_list") 
    
    return render(request,template_name, contexto ) 

productos/templates/productos/nota_credito_list.html
{% extends 'base/base.html' %}

{% block page_content %}
 <div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Listado de Notas De Creditos</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
          <div class="dropdown-header">Opciones</div>
          <!--<a class="dropdown-item" href="{% url 'productos:producto_new' %}"><i class="far fa-calendar-plus"></i> Nuevo Producto</a> -->
          <!--<a class="dropdown-item" onclick="return abrir_modal('{% url 'productos:producto_new' %}')  " href=""><i class="far fa-calendar-plus"></i> Nuevo Producto</a>-->
          <!--<a class="dropdown-item" href="#">Another action</a> 
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a> -->
        </div> 
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
      {% if not obj %}
      	<div class="alert alert-info">No hay Notas de Creditos</div>
      {% else %}
      <table class="table table-striped table-hover" >
      	<thead>
      		<th>id</th>
          <th>Numero De Factura</th>
          <th>Descripcion</th>
          <th>Producto</th>
      		<th>Cantidad</th>
      		<th>Precio</th>
          <th>Total</th>
      	</thead>
      	<tbody>
      		{% for item in obj %}
      			<tr>
      				<td>{{ item.id }}</td>
      				<td>{{ item.no_factura}}</td>
              <td>{{ item.descripcion}}</td>
              <td>{{ item.producto}}</td>
              <td>{{ item.cantidad }}</td>
      				<td>{{ item.precio }}</td>
              <td>{{ item.total }}</td>
      				<td>
              <a class="btn btn-success btn-circle" href="{% url 'productos:nota_credito_print' item.id %}" target="reportes"><i class="fas fa-print"></i></a>
      					<!--  <a href="{% url 'productos:producto_edit' item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a> -->
      				</td>
      			</tr>
      		{% endfor %}
      	</tbody>
      </table>
      {% endif %}
    </div>
  </div>

{% endblock page_content %}

{% block js_page %}
{% endblock %}


 

              

productos/templates/productos/nota_credito_print_one.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Listado de Notas</title>

    <style type="text/css">
    @page {
        size: letter;
        margin: 1cm;
    }
    .table {
        background-color: #c0c1c8;
        text-align: center;
    }
    .table td .numero{
        text-align: center;
    }
    </style>
</head>
<body>
    <div class="container">
        <div class="card">
            <div class="card-header">
                <h4>CFSoft</h4>
            </div>

            <div class="list-group">
                <p>No. Nota de Credito: {{ nota.id}} </p>
                <table class="">
                    <tbody>
                        <tr>
                            <td>Fecha: {{ today }}</td>
                            <td>{{ nota.fecha|date:"d/m/Y"}}</td>
                        </tr>
                        <tr>
                            <td>Nota de credito x Factura</td>
                            <td>{{nota.no_factura}}</td>
                        </tr>
                    </tbody>
                </table>
                <hr>
            </div>


            <table class="table">
                <thead>
                    <tr>
                        <th>Producto</th>
                        <th>Descripcion</th>
                        <th>Cant Dev</th>
                        <th>Precio</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><span class="small">{{ nota.producto}}</span></td>
                        <td class="text">{{ nota.descripcion }}</td>
                        <td class="text">{{ nota.cantidad }}</td>
                        <td class="numero">{{ nota.precio }}</td>
                    </tr>
                          <tr>
                            <td><br></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                          </tr>
                          <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td><h4>Total</h4></td>
                            <td class="numero"><h4>{{ nota.total}}</h4></td>
                          </tr>
                          <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td><h4></h4>Gravada</td>
                            <td class="numero"><h4>{{ nota.gravada}}</h4></td>
                          </tr>
                          <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td><h4></h4>Iva 5%</td>
                            <td class="numero"><h4>{{ nota.iva}}</h4></td>
                          </tr>

                </tbody>
            </table>
        </div>
    </div>
</body>
</html>

productos/templates/productos/producto_del.html
{% extends 'base/base.html' %}

{% block page_content %}
<form method="POST" class="form-inline">
	{% csrf_token %}
	<div class="col-xl-3 col-md-6 mb-4">
		<div class="card border-left-danger shadow h-100 py-2">
			<div class="card-body">
				<div class="row no-gutters align-items-center">
					<div class="col mr-2">
						<div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Eliminar Producto?</div>
						<button type="submit" class="btn btn-danger">Si, Eliminar</button>
						<a href="{% url 'productos:producto_list' %}" class="btn btn-succes"><span class="fa fa-undo"></span>Cancelar</a>
					</div>
					<div class="col-auto">
						<i class="fas fa-comments fa-2x text-gray-300"></i>
					</div>
				</div>
			</div>
		</div>
	</div>
</form>

{% endblock %}



{% block js_page %}
{% endblock %}

productos/templates/productos/producto_form.html
<!-- {% extends 'base/base.html' %} -->

<!--{% block page_content %}  -->
<div class="modal-dialog modal-lg">
    <div class="modal-content">
    {% if obj %}
    <form method="POST" role="form" class="form-inline" action="{% url 'productos:producto_edit' obj.pk %}">
    {% else %} 
    <form method="POST" role="form" class="form-inline" action="{% url 'productos:producto_new' %}">
    {% endif %}
    <!--{% csrf_token %} -->
        <div class="col-xl-12 col-md-12 mb-12">
            {% if obj %}
                <div class="card border-left-warning shadow h-100 py-2">
            {% else %}  
                <div class="card border-left-succes shadow h-100 py-2">
            {% endif %}
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                   <div class="col mr-2">
                       <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            {% if obj %} Editar {% else %} Nuevo Producto {% endif %} </div>
                            <div class="dropdown-divider"></div>
                            {% csrf_token %}
                                <div class="row">
                                    {{ form.as_p }}
                                </div>
                            <div class="dropdown-divider"></div>
                                <div class="row">
                                    <div class="col">
                                        <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span>Guardar</button>
                                    <!--<a href="{% url 'productos:producto_list' %}" class="btn btn-succes"><span class="fa fa-undo"></span>Cancelar</a> -->
                                    <button type="submit" class="btn btn-success" onclick="return cerrar_modal()" >
                                        Cancelar
                                    </button>
                                </div>
                            </div>
                      </div>
                </div>
            </div>
        </div>
    </div>
</form>
    </div>
</div>

<!--
{% endblock %}



{% block js_page %}
{% endblock %} 

productos/templates/productos/producto_inv_list.html
{% extends 'base/base.html' %}

{% block page_content %}
 <div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Listado Inventario</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
          <div class="dropdown-header">Opciones</div>
          <!--<a class="dropdown-item" href="{% url 'productos:producto_new' %}"><i class="far fa-calendar-plus"></i> Nuevo Producto</a> -->
          <a class="dropdown-item" onclick="return abrir_modal('{% url 'productos:producto_new' %}')  " href=""><i class="far fa-calendar-plus"></i> Nuevo Producto</a>
          <!--<a class="dropdown-item" href="#">Another action</a> 
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a> -->
        </div> 
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
      {% if not obj %}
      	<div class="alert alert-info">No hay productos</div>
      {% else %}
      <table class="table table-striped table-hover" >
      	<thead>
      		<th>id</th>
          <th>producto</th>
      		<th>codigo de Producto</th>
          <th>existencia</th>
          <th>precio de venta</th>
      		<th class="all">Opciones</th>
      	</thead>
      	<tbody>
      		{% for item in obj %}
      			<tr>
      				<td>{{ item.id }}</td>
      				<td>{{ item.product_name }}</td>
              <td>{{ item.codigo }}</td>
              <td>{{ item.existencia }}</td>
              <td>{{ item.precio }}</td>
      				<td>
      					<!--  <a href="{% url 'productos:producto_edit' item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a> -->
                <button class="btn btn-primary" onclick="return abrir_modal('{% url 'productos:inv_producto_edit' item.id %}') " ><i class="fas fa-wrench"></i> 
                </button>
                
      					<a href="{% url 'productos:producto_del' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
      				</td>
      			</tr>
      		{% endfor %}   
      	</tbody>
      </table>
      {% endif %}
    </div>
  </div>

{% endblock page_content %}

{% block js_page %}
{% endblock %}


 

              

productos/templates/productos/producto_list.html
{% extends 'base/base.html' %}

{% block page_content %}
 <div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Listado de Productos</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
          <div class="dropdown-header">Opciones</div>
          <!--<a class="dropdown-item" href="{% url 'productos:producto_new' %}"><i class="far fa-calendar-plus"></i> Nuevo Producto</a> -->
          <a class="dropdown-item" onclick="return abrir_modal('{% url 'productos:producto_new' %}')  " href=""><i class="far fa-calendar-plus"></i> Nuevo Producto</a>
          <!--<a class="dropdown-item" href="#">Another action</a> 
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a> -->
        </div> 
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
      {% if not obj %}
      	<div class="alert alert-info">No hay productos</div>
      {% else %}
      <table class="table table-striped table-hover" >
      	<thead>
      		<th>id</th>
          <th>product_name</th>
      		<th>codigo</th>
      		<th>unidad_medida</th>
          <th>categoria</th>
          <th>existencia</th>
          <th>marca</th>
          <th>precio compra</th>
      		<th class="all">Opciones</th>
      	</thead>
      	<tbody>
      		{% for item in obj %}
      			<tr>
      				<td>{{ item.id }}</td>
      				<td>{{ item.product_name }}</td>
              <td>{{ item.codigo }}</td>
      				<td>{{ item.unidad_medida }}</td>
              <td>{{ item.categoria }}</td>
              <td>{{ item.existencia }}</td>
              <td>{{ item.marca }}</td>
              <td>{{ item.precio }}</td>
      				<td>
      					<!--  <a href="{% url 'productos:producto_edit' item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a> -->
                <button class="btn btn-warning btn-circle" onclick="return abrir_modal('{% url 'productos:producto_edit' item.id %}') " ><i class="far fa-edit"></i> 
                </button>
                
      					<a href="{% url 'productos:producto_del' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
      				</td>
      			</tr>
      		{% endfor %}
      	</tbody>
      </table>
      {% endif %}
    </div>
  </div>

{% endblock page_content %}

{% block js_page %}
{% endblock %}


 

              