CFSoft/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('', include( ('bases.urls','bases'), namespace='bases' ) ),
    path('admin/', admin.site.urls),
]

api/urls.py
from django.urls import path, include
from .views import ProductoList, ProductoDetalle, \
    ClienteList


urlpatterns = [
 	path('v1/productos/',ProductoList.as_view(),name='producto_list'),
    path('v1/productos/<str:codigo>',ProductoDetalle.as_view(),name='producto_detalle'),
    path('v1/clientes/',ClienteList.as_view(),name='cliente_list')
    
]

cfsoft/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from Clientes import views 
from productos import views
from ventas import views

"""path('Clientes/', include(('Clientes.urls','Clientes'), namespace='clientes')),"""

urlpatterns = [
    path('', include(('bases.urls','bases'), namespace='bases')), 
    path('proveedor/', include(('proveedor.urls', 'proveedor'), namespace='proveedor')),
    path('productos/', include(('productos.urls','productos'), namespace='productos')),
    path('inventario/', include(('inventario.urls', 'inventario'), namespace='inv')),
    path('ventas/', include(('ventas.urls', 'ventas'), namespace='ventas')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
    path('admin/', admin.site.urls),

]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

productos/urls.py
from django.urls import path

#Local
from productos.views import ProductoView, ProductoNew, ProductoEdit, ProductoDel, InvProductoEdit, ProductoInvView, NotaCreditoView
from .reportes import imprimir_nota

urlpatterns = [
	path('productos/',ProductoView.as_view(), name='producto_list'),
	path('notas_creditos/',NotaCreditoView.as_view(), name='nota_credito_list'), 
	path('inv-productos/',ProductoInvView.as_view(), name='producto_inv_list'),
	path('productos/new',ProductoNew.as_view(), name='producto_new'),
	path('productos/edit/<int:pk>',ProductoEdit.as_view(), name='producto_edit'),
	path('Inventarioproductos/edit/<int:pk>',InvProductoEdit.as_view(), name='inv_producto_edit'),
	path('productos/delete/<int:pk>',ProductoDel.as_view(), name='producto_del'),
	path('notas_creditos/<int:id>/imprimir', imprimir_nota, name="nota_credito_print"),
]

proveedor/urls.py
# Django
from django.urls import path

# Local
from .views import ProveedorView, ProveedorNew, ProveedorEdit, ProveedorDel, PagoView, ComprasDetEdit,ComprasDetView, \
    ComprasView, compras, CompraDetDelete, OrdenComprasView, orden_compras, OrdenView, clienteInactivar, realizarPago, detalle_compras,notaCredito
from .reportes import reporte_compras, imprimir_compra, imprimir_compras_rang

urlpatterns = [
    path('proveedor/', ProveedorView.as_view(), name='proveedor_list'),
    path('proveedor/new', ProveedorNew.as_view(), name='proveedor_new'),
    path('proveedor/edit/<int:pk>', ProveedorEdit.as_view(), name='proveedor_edit'),
    path('proveedor/delete/<int:pk>', ProveedorDel.as_view(), name='proveedor_del'),
    path('compras/listado', reporte_compras, name='compras_print_all'),
    path('compras/<int:compras_id>/imprimir', imprimir_compra, name="compras_print_one"),
    path('compras/imprimir-todas/<str:f1>/<str:f2>', imprimir_compras_rang, name="compras_print_rang"),
    #path('compras/imprimir-todas/<str:f1>/<str:f2>', imprimir_compras_rang, name="pruebas_compras"),

    path('compras/', ComprasView.as_view(), name="compras_list"),
    path('compras_detalle/', ComprasDetView.as_view(), name="compras_det_list"), 
    path('orden_compras/', OrdenComprasView.as_view(), name="orden_compras_list"),
    path('pago/', PagoView.as_view(), name="pago_list"),
    path('compras/new', compras, name="compras_new"),
    path('orden_compras/new', orden_compras, name="orden_compras_new"),
    path('compras/edit/<int:compra_id>', compras, name="compras_edit"),  
    path('compras_detalle/<int:compra_id>/edit/<int:pk>', ComprasDetEdit.as_view(), name="compras_detalle_edit"),
    #path('compras_detalles/edit/<int:id>', ComprasDetEdit.as_view(), name="compras_det_edit"),
    path('compras_detalles/edit/<int:pk>', ComprasDetEdit.as_view(), name="compras_det_edit"),
    path('orden_compras/edit/<int:compra_id>', orden_compras, name="orden_compras_edit"),
    path('compras/<int:compra_id>/delete/<int:pk>', CompraDetDelete.as_view(), name="compras_del"),
    path('orden_compra/estado/<int:id>',clienteInactivar, name="cliente_inactivar"),
    path('pago/<int:id>',realizarPago, name="realizar_pago"),
    path('proveedor/buscar-orden',OrdenView.as_view(), name='buscar_compra'),

    path('compras/notaCred/<int:id>', notaCredito, name="nota_credito")
]

ventas/urls.py
#Django
from django.urls import path,include

#Local

from ventas.views import ClienteView,ClienteNew,ClienteEdit,clienteInactivar,FacturaView,facturas, \
ProductoView, borrar_detalle_factura, cliente_add_modify,orden_facturas,borrar_OrdenDetalle_factura, OrdenFacturaView, \
OrdenView, ordenInactivar, CajaView, CajaNew, CajaEdit, CajaDel, VentaDetEdit, cerrarCaja,productos_vendidos, reporte_ganancias, productos_comprados_prov, notaCredito

from .reportes import imprimir_factura_recibo, imprimir_factura_list, GraficoVentas, GraficoCompras

urlpatterns = [

    path('clientes/',ClienteView.as_view(), name="cliente_list"),
    path('clientes/new',ClienteNew.as_view(), name="cliente_new"),
    path('clientes/<int:pk>',ClienteEdit.as_view(), name="cliente_edit"),
    path('clientes/estado/<int:id>',clienteInactivar, name="cliente_inactivar"),

	path('ventas/',FacturaView.as_view(), name='factura_list'),
    path('ventas-top-productos/',productos_vendidos, name='top_productos_list'),
    path('ventas-reporte-ganancias/',reporte_ganancias, name='reporte_ganancias'),
    path('ventas-reporte-compras/',productos_comprados_prov, name='reporte_comprados'),
    path('orden_ventas/',OrdenFacturaView.as_view(), name='orden_factura_list'),  
   # path('orden_ventas/',OrdenVentaView.as_view(), name='orden_venta_list'),
	path('ventas/new',facturas, name='factura_new'),
    path('ventas/orden_new',orden_facturas, name='orden_new'),
    #path('orden_ventas/new',OrdenVentaNew.as_view(), name="orden_venta_new"),
	path('ventas/edit/<int:id>',facturas, name='factura_edit'),
    path('orden_ventas/edit/<int:id>',orden_facturas, name='orden_factura_edit'),
    path('ventas_detalles/edit/<int:pk>', VentaDetEdit.as_view(), name="ventas_det_edit"),

	path('ventas/buscar-producto',ProductoView.as_view(), name='factura_producto'),
    path('ventas/buscar-orden',OrdenView.as_view(), name='factura_orden'),

	path('ventas/borrar-detalle/<int:id>',borrar_detalle_factura, name="factura_borrar_detalle"),
    path('ventas/borrar-OrdenDetalle/<int:id>',borrar_OrdenDetalle_factura, name="factura_borrar_OrdenDetalle"),


    path('ventas/imprimir-todas/<str:f1>/<str:f2>',imprimir_factura_list, name="factura_imprimir_all"),
    path('ventas/imprimir/<int:id>', imprimir_factura_recibo, name="factura_imprimir_one"),
    path('orden_venta/estado/<int:id>',ordenInactivar, name="orden_inactivar"),
    
    path('ventas/clientes/new/',cliente_add_modify,name="fac_cliente_add"),
    path('ventas/clientes/<int:pk>',cliente_add_modify,name="fac_cliente_mod"),

    path('caja/',CajaView.as_view(), name='caja_list'),
    path('caja/new',CajaNew.as_view(), name='caja_new'),
    path('caja/edit/<int:pk>',CajaEdit.as_view(), name='caja_edit'),
    path('caja/delete/<int:pk>',CajaDel.as_view(), name='caja_del'),
    path('grafico_venta_max/', GraficoVentas, name="grafico_venta_max"),
    path('grafico_compra_max/', GraficoCompras, name="grafico_compra_max"),

    path('cierre/<int:id>',cerrarCaja, name="cierre_caja"),

    path('ventas/notaCred/<int:id>', notaCredito, name="nota_credito")

]

venta/models.py
#Django
from django.db import models

#Local
from bases.models import ClaseModelo, ClaseModelo2
from Clientes.models import Cliente
from productos.models import Producto


""" Encabezado de la factura """

class FacturaEnc(ClaseModelo2):
	cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
	fecha = models.DateTimeField(auto_now_add=True)
	sub_total = models.FloatField(default=0)
	descuento = models.FloatField(default=0)
	total = models.FloatField(default=0)

def __str__(self):
	return '{}'.format(self.id)

def save(self):
	self.total = self.sub_total - self.descuento
	super(facturaEnc,self).save()

class Meta:
	verbose_name_plural = "Encabezado de Facturas"
	verbose_name = "Encabezado Factura"


 
""" Detalle de la factura """

class FacturaDet(ClaseModelo2):
	factura = models.ForeignKey(FacturaEnc, on_delete=models.CASCADE)
	producto = m odels.ForeignKey(Producto, on_delete=models.CASCADE)
	cantidad = models.BigIntegerField(default=0)
	precio = models.FloatField(default=0)
	sub_total = models.FloatField(default=0)
	descuento = models.FloatField(default=0)
	total = models.FloatField(default=0)

def __str__(self):
	return '{}'.format(self.producto)	

def save(self):
	self.sub_total = float(float(int(self.cantidad)) * float(self.precio))
	self.total = self.sub_total - float(self.descuento)
	super(FacturaDet, self).save()

class Meta:
	verbose_name_plural = "Detalles Facturas"
	verbose_name = "Detalle Factura"

ventas/models.py
#Django
from django.db import models

#Para los signals
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.db.models import Sum
from django.utils import timezone
#from datetime import date
import datetime
#Local
from bases.models import ClaseModelo, ClaseModelo2, ClaseModeloUsuario
from productos.models import Producto
from proveedor.models import ComprasEnc, ComprasDet


class Cliente(ClaseModelo):
    NAT='Natural'
    JUR='Jurídica'
    TIPO_CLIENTE = [
        (NAT,'Natural'),
        (JUR,'Jurídica')
    ]
    nombres = models.CharField(
        max_length=100
    )
    apellidos = models.CharField(
        max_length=100
    )
    celular = models.CharField(
        max_length=20,
        null=True,
        blank=True
    )
    tipo=models.CharField(
        max_length=10,
        choices=TIPO_CLIENTE,
        default=NAT
    )

    def __str__(self):
        return '{} {}'.format(self.apellidos,self.nombres)

    def save(self, *args, **kwargs):
        self.nombres = self.nombres.upper()
        self.apellidos = self.apellidos.upper()
        super(Cliente, self).save( *args, **kwargs)

    class Meta:
        verbose_name_plural = "Clientes"


class FacturaEnc(ClaseModelo2):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    descripcion = models.TextField(blank=True, null=True)
    #fecha = models.DateTimeField(auto_now_add=True)
    fecha = models.DateTimeField(null=True, blank=True)
    no_factura = models.CharField(max_length=100)
    sub_total=models.FloatField(default=0)
    descuento=models.FloatField(default=0)
    total=models.FloatField(default=0)
    no_timbrado = models.CharField(max_length=8)
    fecha_fin_timbrado = models.DateField(null=True, blank=True)
    fecha_ini_timbrado = models.DateField(null=True, blank=True)

    def __str__(self):
        return '{}'.format(self.id)

    def save(self,**kwargs):
        self.total = self.sub_total - self.descuento
        super(FacturaEnc,self).save()

    class Meta:
        verbose_name_plural = "Encabezado Facturas"
        verbose_name="Encabezado Factura"
        permissions = [
            ('sup_caja_facturaenc','Permisos de Supervisor de Caja Encabezado')
        ]


class Caja(ClaseModelo2):
    fac = models.ForeignKey(FacturaEnc,on_delete=models.CASCADE, null=True)
    comp = models.ForeignKey(ComprasEnc,on_delete=models.CASCADE, null=True)
    descripcion = models.TextField(blank=True, null=True)
    #fecha = models.DateTimeField(default=timezone.now,null=True)
    fecha = models.DateTimeField(default=datetime.datetime.now,null=True)
    #fecha = models.DateTimeField(null=True, blank=True)
    entrada = models.BigIntegerField(default=0,null=True)
    salida = models.BigIntegerField(default=0,null=True)
    saldo_actual = models.BigIntegerField(default=0,null=True)


    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):        
        if self.salida != 0:
            cant = Caja.objects.all().count()
            cajalist = Caja.objects.all()
            saldo = cajalist[cant-1].saldo_actual
            self.saldo_actual = saldo - self.salida
        else:
            cant = Caja.objects.all().count()
            if cant >=1:
                cajalist = Caja.objects.all()
                saldo = cajalist[cant-1].saldo_actual
                self.saldo_actual = saldo + self.entrada
            else:
                self.saldo_actual = self.entrada
        super(Caja,self).save()

    class Meta:
        verbose_name_plural= "Cajas"

class FacturaDet(ClaseModelo2):
    factura = models.ForeignKey(FacturaEnc,on_delete=models.CASCADE)
    producto=models.ForeignKey(Producto,on_delete=models.CASCADE)
    fecha_detalle = models.DateTimeField(null=True, blank=True)
    cantidad=models.BigIntegerField(default=0)
    precio=models.FloatField(default=0)
    sub_total=models.FloatField(default=0)
    descuento=models.FloatField(default=0)
    total=models.FloatField(default=0)

    def __str__(self):
        #return '{}'.format(self.producto)
        return f'{self.factura}, {self.producto}, {self.cantidad}, {self.precio}, {self.sub_total} , {self.total}'

    def save(self):
        self.sub_total = float(float(int(self.cantidad)) * float(self.precio))
        self.total = self.sub_total - float(self.descuento)
        super(FacturaDet, self).save()
    
    class Meta:
        verbose_name_plural = "Detalles Facturas"
        verbose_name="Detalle Factura"
        permissions = [
            ('sup_caja_facturadet','Permisos de Supervisor de Caja Detalle')
        ]


@receiver(post_save, sender=FacturaDet)
def detalle_fac_guardar(sender,instance,**kwargs):
    factura_id = instance.factura.id
    producto_id = instance.producto.id
    enc = FacturaEnc.objects.filter(pk=factura_id).first()
    if enc:

        sub_total = FacturaDet.objects.filter(factura=factura_id).aggregate(Sum('sub_total'))
        descuento = FacturaDet.objects.filter(factura=factura_id).aggregate(Sum('descuento'))

        enc.sub_total = sub_total['sub_total__sum']
        enc.descuento = descuento['descuento__sum']
        total_detalle = enc.sub_total
        enc.save()

    c = Caja.objects.filter(fac=factura_id).first()
    # si ya existe la caja entonces editamos
    """if not c:
        enc = FacturaEnc.objects.filter(pk=factura_id).first()
        cant = Caja.objects.all().count()
        cajalist = Caja.objects.all()
        #total_detalle = enc.total
        saldo = cajalist[cant-1].saldo_actual
        saldo_actual = total_detalle + saldo

        caja = Caja (
            fac = enc,
            descripcion = 'VENTA',
            entrada = total_detalle,
            salida = 0,
            saldo_actual = saldo_actual
        )

        caja.save() """


    prod=Producto.objects.filter(pk=producto_id).first()
    #import pdb; pdb.set_trace()
    if prod:
        cantidad = int(prod.existencia) - int(instance.cantidad)
        prod.existencia = cantidad
        prod.save()


class OrdenFacturaEnc(ClaseModelo2):
    #caja = models.ForeignKey(Caja, on_delete=models.CASCADE)
    descripcion = models.TextField(blank=True, null=True)
    fecha = models.DateTimeField(auto_now_add=True, null=True)
    sub_total=models.FloatField(default=0)
    descuento=models.FloatField(default=0)
    total=models.FloatField(default=0)

    def __str__(self):
        return '{}'.format(self.id)

    def save(self):
        #self.descripcion = self.descripcion.upper()
        self.total = self.sub_total - self.descuento
        super(OrdenFacturaEnc,self).save()

    class Meta:
        verbose_name_plural = "Encabezado Orden Facturas"
        verbose_name="Encabezado Orden Factura"
        permissions = [
            ('sup_caja_facturaenc','Permisos de Supervisor de Caja Orden Encabezado')
        ]

class OrdenFacturaDet(ClaseModelo2):
    factura = models.ForeignKey(OrdenFacturaEnc,on_delete=models.CASCADE)
    producto=models.ForeignKey(Producto,on_delete=models.CASCADE)
    cantidad=models.BigIntegerField(default=0)
    precio=models.FloatField(default=0)
    sub_total=models.FloatField(default=0)
    #descuento=models.FloatField(default=0)
    total=models.FloatField(default=0)

    def __str__(self):
        #return '{}'.format(self.producto)
        return f'{self.factura}, {self.producto}, {self.cantidad}, {self.precio}, {self.sub_total} , {self.total}'

    def save(self):
        self.sub_total = float(float(self.cantidad)) * float(self.precio)
        self.total = self.sub_total 
        super(OrdenFacturaDet, self).save()
    
    class Meta:
        verbose_name_plural = "Detalles Ordenes Facturas"
        verbose_name="Detalle orden Factura"
        permissions = [
            ('sup_caja_facturadet','Permisos de Supervisor de Caja Detalle')
        ]

ventas/templates/ventas/factura_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<div class="card shadow mb-4">
  <!-- Card Header - Dropdown -->
  <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
    <h6 class="m-0 font-weight-bold text-primary">Listado de Facturas</h6>
    <!-- <div class="dropdown no-arrow">
      <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
        <div class="dropdown-header">Acciones:</div>
        <a class="dropdown-item" onclick="return abrir_modal('{% url 'ventas:cliente_new' %}')" href="#"><i class="far fa-calendar-plus"></i> Nuevo</a>
      </div>
    </div> -->
  </div>
  <!-- Card Body -->
  <div class="card-body">
    <div class="row">
      <div class="col-md-4">
        <input type="text" class="form-class" name="f1" id="f1" readonly>
      </div>
      <div class="col-md-4">
        <input type="text" class="form-class" name="f2" id="f2" readonly>
      </div>
      <div class="col-md-4">
        <button class="btn btn-warning" type="button" id="btnPrint">Imprimir</button>
      </div>
    </div>
    <hr>

    
    {% if not obj %}
    <div class="alert alert-info">No Hay Facturas</div>
    {% endif %}
    <div class="buttons-toolbar">
        <a class="btn btn-success" href="{% url 'ventas:factura_new' %}"><i cass="far fa-calendar-plus"></i> Nueva Factura Venta</a>
    </div>

    <table 
      id="table"
      data-toggle="table"
      data-pagination="true"
      data-search="true"
      data-show-columns="true"
      data-show-toggle="true"
      data-show-fullscreen="true"
      data-toolbar=".buttons-toolbar"
      data-locale="es-NI"
    >
    <thead>
      <th data-sortable="true" data-field="id">No.</th>
      <th data-sortable="true" data-field="nombres">Cliente</th>
      <th data-sortable="true" data-field="apellidos">Total</th>
      <th data-field="estado">Estado</th>
      <th class="all">Acciones</th>
    </thead>
    <tbody>
      {% for item in obj%}
      <tr>
        <td>{{ item.id }}</td>
        <td>{{ item.cliente }}</td>
        <td>{{ item.total }}</td>
        <td>{{item.estado|yesno:"Activo,Inactivo"}}</td>
        <td>
          <a href="{% url 'ventas:factura_edit' item.id %}" class="href btn btn-warning btn-circle">
              <i class="far fa-edit"></i>
          </a>
          <a class="btn btn-info" href="{% url 'ventas:nota_credito' item.id %} ">Nota de Crédito</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>


    </table>
  </div>
</div>
{% endblock %}
{% block js_page %}
<script>
$(function(){
  $("#f1, #f2").datetimepicker({
      format: 'Y-m-d',
      timepicker:false
  });

  $("#btnPrint").click(function(e){
    e.preventDefault();
    var f1,f2;
    f1 = $("#f1").val();
    f2 = $("#f2").val();
    if(f1=="" || f1==null){
      f1="2019-06-01";
    }
    if(f2=="" || f2==null){
      var d = new Date();
      var f2 = d.getFullYear() + "-" + (d.getMonth()+1) + "-" + d.getDate();
    }
    
    var url = "imprimir-todas/" + f1 + "/" + f2;

    window.open(url,'facturas');
    
  });
});
</script>
{% endblock %}

ventas/templates/ventas/nota_credito_venta.html
{% extends 'base/base.html'%}
{% block page_content %}
    <form method="POST" id="frmNotaDeCredito">
        {% csrf_token %}
        <div class="col-xl-12 col-md-12 mb-12">
            <div class="card border-left-warning shadow h-100 py-2">
            <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                </div>
                                <h1> Nota de Crédito</h1>
                                <div class="dropdown-divider"></div>
                                <div class="row">
                                    <!-- Inicio Izquierda -->
                                    <div class="col-6">
                                        <!-- Inicio Encabezado -->
                                        <label for="cantidad" class="col-sm-3 col-form-label">Cantidad a devolver</label>
                                            <div class="col-sm-5">
                                                <input type="number"  class="form-control" name="cantidad" id="cantidad" value="" required>
                                            </div>
                                        <label for="cantidad" class="col-sm-3 col-form-label">Código del Producto</label>
                                            <div class="col-sm-5">
                                                <input type="number" class="form-control" name="codigo" id="codigo" value="" required>
                                            </div>
                                    </div>
                                </div>
                                        <!-- Fin Encabezado -->
                                    </div>
                                    <!-- Fin Izquierda -->
                                    <!-- Inicio Derecha -->
                                    <div class="col-6">
                                        <div class="row">
                                            <div class="col"> 
                                            </div>
                                        </div> 
                                        <!--fin del row dela tabla de ordenes de compra-->
                            
                                        <!-- Botones -->
                                        
                                        <div class="row">
                                            <div class="col-6">
                                                <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Generar Nota de Crédito</button>
                                                <a href="{% url 'proveedor:compras_list' %}" class="btn btn-success"><i class="far fa-hand-point-left"></i> Cancelar</a>
                                            </div>
                                        </div>
                                        <!-- Fin Botones -->
                                    </div>
                                    <!-- Fin Derecha -->
                                </div>
                                <!-- Inicio Detalle -->
                                <div class="row">
                                    <div class="col">
                                        <table class="table table-striped table-hover dt-responsive nowrap" style="width:100%">
                                            <thead>
                                                <th>Codigo Producto</th>
                                                <th>Producto</th>
                                                <th>Cantidad</th>
                                                <th>Precio</th>
                                                <th>Sub Total</th>
                                                <th>Desc.</th>
                                                <th>Total</th>
                                            </thead>
                                            <tbody>
                                               {% for item in detalle %}
                                                <tr>
                                                <td>{{ item.producto }}</td>
                                                <td>{{ item.producto.product_name }}</td>
                                                <td>{{ item.cantidad }}</td>
                                                <td>{{ item.precio_prv }}</td>
                                                <td>{{ item.sub_total }}</td>
                                                <td>{{ item.descuento }}</td>
                                                <td>{{ item.total }}</td>
                                                </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <!-- Fin Detalle -->
                            </div>
                        </div>
                </div>
        </div>
    </form>
{% endblock %}
{% block js_page %} 
<script>
    $(function () {

        $("#id_fecha_compra, #id_fecha_factura, #id_fecha_ini_timbrado, #id_fecha_fin_timbrado").datetimepicker({
            format: 'Y-m-d',
            timepicker:false
        });

        $("#sidebarToggle").click();

        $('.table').DataTable({
            "pageLength": 2,
            "language": {
            "sProcessing": "Procesando...",
            "sLengthMenu": "Mostrar _MENU_ registros",
            "sZeroRecords": "No se encontraron resultados",
            "sEmptyTable": "Ningún dato disponible en esta tabla",
            "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
            "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
            "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
            "sInfoPostFix": "",
            "sSearch": "Buscar:",
            "sUrl": "",
            "sInfoThousands": ",",
            "sLoadingRecords": "Cargando...",
            "oPaginate": {
                "sFirst": "<span class='fa fa-angle-double-left'></span>",
                "sLast": "<span class='fa fa-angle-double-right'></span>",
                "sNext": "<span class='fa fa-angle-right'></span>",
                "sPrevious": "<span class='fa fa-angle-left'></span>"
            },
            "oAria": {
                "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                "sSortDescending": ": Activar para ordenar la columna de manera descendente"
            }
            }
        });

        /*Validar Envio de Detalle*/

        $("#frmNotaDeCredito").submit(function(e){ 


        /*Fin Validar Envio de Detalle*/

    });

    function selectProducto(id,descripcion)
    {
        $('#id_cantidad_detalle').val(0);
        $(`#id_precio_detalle`).val(0);
        $('#id_descuento_detalle').val(0);

        $('#id_sub_total_detalle').val(0);
        $('#id_total_detalle').val(0);

        $('#id_id_producto').val(+id);
        $('#id_descripcion_producto').val(descripcion);
        $('#id_cantidad_detalle').focus();
        $('#id_cantidad_detalle').select();

        $('.table').DataTable().search('').draw();
    }


</script>
{% endblock %}

ventas/templates/ventas/orden_venta_del.html
{% extends 'base/base.html' %}

{% block page_content %}
<form method="POST" class="form-inline">
	{% csrf_token %}
	<div class="col-xl-3 col-md-6 mb-4">
		<div class="card border-left-danger shadow h-100 py-2">
			<div class="card-body">
				<div class="row no-gutters align-items-center">
					<div class="col mr-2">
						<div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Eliminar Orden?</div>
						<button type="submit" class="btn btn-danger">Si, Eliminar</button>
						<a href="{% url 'ventas:orden_venta_list' %}" class="btn btn-succes"><span class="fa fa-undo"></span>Cancelar</a>
					</div>
					<div class="col-auto">
						<i class="fas fa-comments fa-2x text-gray-300"></i>
					</div>
				</div>
			</div>
		</div>
	</div>
</form>

{% endblock %}



{% block js_page %}
{% endblock %}