CFSoft/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('', include( ('bases.urls','bases'), namespace='bases' ) ),
    path('admin/', admin.site.urls),
]

api/urls.py
from django.urls import path, include
from .views import ProductoList, ProductoDetalle, \
    ClienteList


urlpatterns = [
 	path('v1/productos/',ProductoList.as_view(),name='producto_list'),
    path('v1/productos/<str:codigo>',ProductoDetalle.as_view(),name='producto_detalle'),
    path('v1/clientes/',ClienteList.as_view(),name='cliente_list')
    
]

cfsoft/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from Clientes import views 
from productos import views
from ventas import views

"""path('Clientes/', include(('Clientes.urls','Clientes'), namespace='clientes')),"""

urlpatterns = [
    path('', include(('bases.urls','bases'), namespace='bases')), 
    path('proveedor/', include(('proveedor.urls', 'proveedor'), namespace='proveedor')),
    path('productos/', include(('productos.urls','productos'), namespace='productos')),
    path('inventario/', include(('inventario.urls', 'inventario'), namespace='inv')),
    path('ventas/', include(('ventas.urls', 'ventas'), namespace='ventas')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
    path('admin/', admin.site.urls),

]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

inventario/urls.py
from django.urls import path

from .views import CategoriaView, CategoriaNew, CategoriaEdit, CategoriaDel, \
    SubCategoriaView, SubCategoriaNew, SubCategoriaEdit, SubCategoriaDel

urlpatterns = [
    path('categorias/', CategoriaView.as_view(), name='categoria_list'),
    path('categorias/new', CategoriaNew.as_view(), name='categoria_new'),
    path('categorias/edit/<int:pk>', CategoriaEdit.as_view(), name='categoria_edit'),
    path('categorias/delete/<int:pk>', CategoriaDel.as_view(), name='categoria_del'),

    path('subcategorias/', SubCategoriaView.as_view(), name='subcategoria_list'),
    path('subcategorias/new', SubCategoriaNew.as_view(), name='subcategoria_new'),
    path('subcategorias/edit/<int:pk>', SubCategoriaEdit.as_view(), name='subcategoria_edit'),
    path('subcategorias/delete/<int:pk>', SubCategoriaDel.as_view(), name='subcategoria_del'),

]

bases/models.py
# Django
from django.db import models
from django.contrib.auth.models import User
from django_userforeignkey.models.fields import UserForeignKey


class ClaseModeloInv(models.Model):
    estado = models.BooleanField(default=True)
    fc = models.DateTimeField(auto_now_add=True)
    fm = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class ClaseModelo(models.Model):
    estado = models.BooleanField(default=True)
    fc = models.DateTimeField(auto_now_add=True, null=True)
    fm = models.DateTimeField(auto_now=True)
    uc = models.ForeignKey(User, on_delete=models.CASCADE)
    um = models.IntegerField(blank=True, null=True)

    class Meta:
        abstract = True


class ClaseModelo2(models.Model):
    estado = models.BooleanField(default=True)
    fc = models.DateTimeField(auto_now_add=True, null=True)
    fm = models.DateTimeField(auto_now=True, null=True)
    uc = UserForeignKey(auto_user_add=True, related_name='+')
    um = UserForeignKey(auto_user=True, related_name='+')

    class Meta:
        abstract = True


class ClaseModeloUsuario(models.Model):
    cedula = models.CharField(max_length=50, blank=True)
    nombre = models.CharField(max_length=50, blank=True)
    apellido = models.CharField(max_length=50, blank=True)
    ruc = models.CharField(max_length=50, blank=True)
    email = models.CharField(max_length=50, blank=True)
    telefono = models.CharField(max_length=50, blank=True)
    direccion = models.CharField(max_length=50, blank=True)

    class Meta:
        abstract = True

class Idioma(models.Model):
    nombre = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural = "Idiomas"

    def __str__(self):
        return self.nombre


class Frase(models.Model):
    idioma = models.ForeignKey(Idioma,on_delete=models.CASCADE)
    autor = models.CharField(max_length=50,default="Anónimo")
    frase = models.TextField(null=True,blank=True)

    class Meta:
        verbose_name_plural = "Frases"

    def __str__(self):
        return "{} - {}".format(self.autor,self.idioma)

inventario/models.py
from django.db import models

from bases.models import ClaseModelo, ClaseModeloInv


class Categoria(ClaseModeloInv):
    descripcion = models.CharField(
        max_length=100,
        help_text='Descripcion de la categoria',
        unique=True
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    """def save(self):
        self.descripcion = self.descripcion.upper()
        super(Categoria, self).save()"""

    class Meta:
        verbose_name_plural = "Categorias"


class SubCategoria(ClaseModeloInv):
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    descripcion = models.CharField(
        max_length=100,
        help_text='Descripcion de la categoria',
    )

    def __str__(self):
        return '{}:{}'.format(self.categoria.descripcion, self.descripcion)

    class Meta:
        verbose_name_plural = "Sub Categorias"
        unique_together = ('categoria', 'descripcion')

inventario/forms.py
from django import forms

from .models import Categoria, SubCategoria


class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['descripcion', 'estado']
        labels = {'descripcion': "Descripcion de la categoria", "estado": "Estado"}
        widget = {'descripcion': forms.DateInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({'class': 'form-control'})


class SubCategoriaForm(forms.ModelForm):
    categoria = forms.ModelChoiceField(
        queryset=Categoria.objects.filter(estado=True)
            .order_by('descripcion')
    )

    class Meta:
        model = SubCategoria
        fields = ['categoria', 'descripcion', 'estado']
        labels = {'descripcion': "Sub categoria", "estado": "Estado"}
        widget = {'descripcion': forms.DateInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({'class': 'form-control'})

        self.fields['categoria'].empty_label = "Seleccione Categoria"

inventario/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Categoria, SubCategoria
from .forms import CategoriaForm, SubCategoriaForm


class CategoriaView(LoginRequiredMixin, generic.ListView):
    model = Categoria
    template_name = "inv/categoria_list.html"
    context_object_name = "obj"
    login_url = 'bases:login'


class CategoriaNew(LoginRequiredMixin, generic.CreateView):
    model = Categoria
    template_name = "inv/categoria_form.html"
    context_object_name = "obj"
    form_class = CategoriaForm
    success_url = reverse_lazy("inv:categoria_list")
    login_url = "bases:login"

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)


class CategoriaEdit(LoginRequiredMixin, generic.UpdateView):
    model = Categoria
    template_name = "inv/categoria_form.html"
    context_object_name = "obj"
    form_class = CategoriaForm
    success_url = reverse_lazy("inv:categoria_list")
    login_url = "bases:login"

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)


class CategoriaDel(LoginRequiredMixin, generic.DeleteView):
    model = Categoria
    template_name = "inv/categoria_del.html"
    context_object_name = "obj"
    success_url = reverse_lazy("inv:categoria_list")


class SubCategoriaView(LoginRequiredMixin, generic.ListView):
    model = SubCategoria
    template_name = "inv/subcategoria_list.html"
    context_object_name = "obj"
    login_url = 'bases:login'


class SubCategoriaNew(LoginRequiredMixin, generic.CreateView):
    model = SubCategoria
    template_name = "inv/subcategoria_form.html"
    context_object_name = "obj"
    form_class = SubCategoriaForm
    success_url = reverse_lazy("inv:subcategoria_list")
    login_url = "bases:login"

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)


class SubCategoriaEdit(LoginRequiredMixin, generic.UpdateView):
    model = SubCategoria
    template_name = "inv/subcategoria_form.html"
    context_object_name = "obj"
    form_class = SubCategoriaForm
    success_url = reverse_lazy("inv:subcategoria_list")
    login_url = "bases:login"

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)


class SubCategoriaDel(LoginRequiredMixin, generic.DeleteView):
    model = SubCategoria
    template_name = "inv/categoria_del.html"
    context_object_name = "obj"
    success_url = reverse_lazy("inv:subcategoria_list")

inventario/templates/inv/categoria_del.html
{% extends 'base/base.html' %}

{% block page_content %}
<form method="POST" class="form-inline">
	{% csrf_token %}
	<div class="col-xl-3 col-md-6 mb-4">
		<div class="card border-left-danger shadow h-100 py-2">
			<div class="card-body">
				<div class="row no-gutters align-items-center">
					<div class="col mr-2">
						<div class="text-xs font-weight-bold text-warning text-uppercase mb-1">¿Eliminar Sub Categoria {{ obj.descripcion }}?</div>
						<button type="submit" class="btn btn-danger">Si, Eliminar</button>
						<!-- <a href="{% url 'inv:categoria_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>-->
                        <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>

					</div>
					<div class="col-auto">
						<i class="fas fa-comments fa-2x text-gray-300"></i>
					</div>
				</div>
			</div>
		</div>
	</div>
</form>

{% endblock %}

inventario/templates/inv/categoria_form.html
{% extends 'base/base.html' %}

{% block page_content %}
    <form method="POST" class="form-inline">
        {% csrf_token %}
        <div class="col-xl-6 col-md-6 mb-6">
            {% if obj %}
            <div class="card border-left-success shadow h-100 py-2">
            {% else %}
            <div class="card border-left-warning shadow h-100 py-2">
            {% endif %}
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                {% if obj %} Editar {% else %} Nueva Categoria {% endif %}
                            </div>
                            <div class="dropdown-divider"></div>
                            <div class="row">
                                <div class="col-10">
                                    <div class="input-group">
                                        <input type="text" name="descripcion" maxlength="100" class="form-control" required id="id_descripcion" placeholder="Descripcion"
                                        value="{% if obj %} {{ obj.descripcion }} {% endif %}">
                                    </div>
                                </div>
                                <div class="col-2">
                                    <div class="form-group">
                                        <label for="id_estado">Estado</label>
                                        <input type="checkbox" name="estado" class="form-control" id="id_estado"
                                        {% if obj.estado %} checked {% endif %}>
                                    </div>
                                </div>
                            </div>
                            <div class="dropdown-divider"></div>
                            <div class="row">
                                <div class="col">
                                    <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                                    <a href="{% url 'inv:categoria_list' %}" class="btn btn-success"><span class="fa fa-undo"></span> Cancelar</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            </div>
        </div>>
    </form>
{% endblock %}
{% block js_page %}
{% endblock %}

inventario/templates/inv/categoria_list.html
{% extends 'base/base.html' %}

{% block page_content %}
     <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
              <h6 class="m-0 font-weight-bold text-primary">Listado de Categorias</h6>
              <div class="dropdown no-arrow">
                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                  <div class="dropdown-header">Acciones</div>
                  <a class="dropdown-item" href="{% url 'inv:categoria_new' %}"><i class="far fa-calendar-plus"></i> Nueva</a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#">Something else here</a>
                </div>
              </div>
            </div>
            <!-- Card Body -->
            <div class="card-body">
                {% if not obj %}
                    <div class="alert alert-info">No hay Categorías</div>
                {% else %}
                <table class="table table-striped table-hover">
                    <thead>
                        <th>Id</th>
                        <th>Descripcion</th>
                        <th>Estado</th>
                        <th>F. Creado</th>
                        <th>F. Modif.</th>
                        <th class="all">Acciones</th>
                    </thead>>
                    <tbody>
                        {% for item in obj %}
                            <tr>
                                <td>{{ item.id }}</td>
                                <td>{{ item.descripcion }}</td>
                                <td>{{ item.estado|yesno:"Activo,Inactivo" }}</td>
                                <td>{{ item.fc|date:"d/m/Y H:i:s" }}</td>
                                <td>{{ item.fm|date:"d/m/Y H:i:s" }}</td>
                                <td>
                                    <a href="{% url 'inv:categoria_edit' item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
                                      <a href="{% url 'inv:categoria_del' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>>
                </table>
                {% endif %}
            </div>
          </div>
{% endblock %}

{% block js_page %}
    <script>
        //Call the dataTables
        $(document).ready(function() {
            $('.table').DataTable();
        })
    </script>
{% endblock %}

inventario/templates/inv/subcategoria_form.html
{% extends 'base/base.html' %}

{% block page_content %}
    <form method="POST" class="form-inline">
        {% csrf_token %}
        <div class="col-xl-12 col-md-12 mb-12">
            {% if obj %}
            <div class="card border-left-success shadow h-100 py-2">
            {% else %}
            <div class="card border-left-warning shadow h-100 py-2">
            {% endif %}
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                {% if obj %} Editar {% else %} Nueva {% endif %} Sub categoria
                            </div>
                            <div class="dropdown-divider"></div>
                            <div class="row">
                                <div class="col-5">
                                    <div class="input-group">
                                        <!--<input type="text" name="descripcion" maxlength="100" class="form-control" required id="id_descripcion" placeholder="Descripcion"
                                        value="{% if obj %} {{ obj.descripcion }} {% endif %}">-->
                                        {{ form.categoria }}
                                    </div>
                                </div>
                                <div class="col-5">
                                    <div class="input-group">
                                        <!--<input type="text" name="descripcion" maxlength="100" class="form-control" required id="id_descripcion" placeholder="Descripcion"
                                        value="{% if obj %} {{ obj.descripcion }} {% endif %}">-->
                                        {{ form.descripcion }}
                                    </div>
                                </div>
                                <div class="col-2">
                                    <div class="input-group">
                                        <!--<label for="id_estado">Estado</label>
                                        <input type="checkbox" name="estado" class="form-control" id="id_estado"
                                        {% if obj.estado %} checked {% endif %} > -->
                                        {{ form.estado }}
                                    </div>
                                </div>
                                <!-- {{ form.as_p }} -->
                            </div>
                            <div class="dropdown-divider"></div>
                            <div class="row">
                                <div class="col">
                                    <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                                    <a href="{% url 'inv:subcategoria_list' %}" class="btn btn-success"><span class="fa fa-undo"></span> Cancelar</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            </div>
        </div>>
    </form>
{% endblock %}
{% block js_page %}
{% endblock %}

inventario/templates/inv/subcategoria_list.html
{% extends 'base/base.html' %}

{% block page_content %}
     <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
              <h6 class="m-0 font-weight-bold text-primary">Listado de Sub Categorias</h6>
              <div class="dropdown no-arrow">
                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                  <div class="dropdown-header">Acciones</div>
                  <a class="dropdown-item" href="{% url 'inv:subcategoria_new' %}"><i class="far fa-calendar-plus"></i> Nueva</a>
                </div>
              </div>
            </div>
            <!-- Card Body -->
            <div class="card-body">
                {% if not obj %}
                    <div class="alert alert-info">No hay Sub Categorías</div>
                {% else %}
                <table class="table table-striped table-hover">
                    <thead>
                        <th>Categoria</th>
                        <th>Id</th>
                        <th>Descripcion</th>
                        <th>Estado</th>
                        <th>F. Creado</th>
                        <th>F. Modif.</th>
                        <th class="all">Acciones</th>
                    </thead>>
                    <tbody>
                        {% for item in obj %}
                            <tr>
                                <td>{{ item.categoria }}</td>
                                <td>{{ item.id }}</td>
                                <td>{{ item.descripcion }}</td>
                                <td>{{ item.estado|yesno:"Activo,Inactivo" }}</td>
                                <td>{{ item.fc|date:"d/m/Y H:i:s" }}</td>
                                <td>{{ item.fm|date:"d/m/Y H:i:s" }}</td>
                                <td>
                                    <a href="{% url 'inv:subcategoria_edit' item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
                                      <a href="{% url 'inv:subcategoria_del' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>>
                </table>
                {% endif %}
            </div>
          </div>
{% endblock %}

{% block js_page %}
    <script>
        //Call the dataTables
        $(document).ready(function() {
            $('.table').DataTable();
        })
    </script>
{% endblock %}